# Generated by Django 5.2.8 on 2025-11-10 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_email_verified_remove_user_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='last_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
