# Generated by Django 5.2.8 on 2025-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailotp_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
