# Generated by Django 5.2.8 on 2025-11-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
