# Generated by Django 5.2.8 on 2025-12-04 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_remove_offer_main_category_remove_offer_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discountType', models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat Amount')], max_length=20)),
                ('discountValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userLimit', models.PositiveIntegerField(default=1)),
                ('minCartValue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validFrom', models.DateTimeField()),
                ('validTill', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory')),
            ],
        ),
    ]
