# Generated by Django 5.2.8 on 2025-12-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='ticketId',
            new_name='ticket_id',
        ),
    ]
