# Generated by Django 5.2.8 on 2025-11-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
