# Generated by Django 5.2.8 on 2025-11-23 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_delivered_at'),
        ('users', '0008_delete_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('REFUND', 'Refund'), ('REPLACEMENT', 'Replacement')], max_length=20)),
                ('reason', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/%d/')),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('refund_mode', models.CharField(blank=True, choices=[('WALLET', 'Wallet Refund'), ('ORIGINAL', 'Original Payment Mode'), ('BANK', 'Bank Transfer')], max_length=20, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKED_UP', 'Item Picked Up'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refund Completed'), ('DECLINED', 'Declined')], default='REQUESTED', max_length=25)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='shop.orderitem')),
                ('pickup_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_pickups', to='users.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
