# Generated by Django 5.2.8 on 2025-11-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_returnrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='refund_mode',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='return_type',
        ),
    ]
