# Generated by Django 5.2.8 on 2025-11-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_returnrequest_refund_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
