# Generated by Django 5.2.8 on 2025-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='offer',
            name='main_category',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids')], max_length=10, null=True),
        ),
    ]
