# Generated by Django 5.2.8 on 2025-12-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_category_offer_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_offers', to='products.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_offers', to='products.subcategory'),
        ),
    ]
