# Generated by Django 5.2.8 on 2025-12-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_offer_product_remove_offer_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_offers', to='products.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='category_offers', to='products.subcategory'),
        ),
    ]
