# Generated by Django 5.2.8 on 2025-12-13 10:25

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_offer_main_category_remove_offer_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': [models.OrderBy(django.db.models.functions.comparison.Cast('size', models.IntegerField()))]},
        ),
    ]
