# Generated by Django 5.2.8 on 2025-12-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productvariant_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
